### ISSUE TITLE
ça marche pas

### ISSUE THREAD

**Issue by Zaklo** [juliendargelos/nuxt-lightningcss#1]
ça marche pas

**Comment by juliendargelos** [comment]
mh non, vous avez la bonne version de Nuxt ?

https://github.com/juliendargelos/nuxt-lightningcss/blob/90a3e8979182c5bb549c42bbc894f0c553ffc9c8/package.json#L58-L60

**Comment by Zaklo** [comment]
yes

**Comment by juliendargelos** [comment]
Est-ce que vous avez des `@import` avec des urls externes genre google fonts ?

**Comment by juliendargelos** [comment]
bah je sais pas j'ai jamais rencontré ce pb, j'ai envie de dire faites un repo de repro ?

**Comment by juliendargelos** [comment]
1bf1f0c
